### ISSUE TITLE
so is this thing not a thing anymore?

### ISSUE THREAD

**Issue by rchrdnsh** [RevillWeb/rebel-router#6]
Hi Leon :-)

I'm looking around and learning about routing and noticed your router as well as the other ones that were mentioned on twitter. Anyway, I'm curious if you are still trying to develop this or if you think the other options that have been mentioned in other places are better choices.

Cheers, 

R

**Comment by RevillWeb** [comment]
Hey! As it stands this project is probably at MVP stage and I've been unable to take it further due to time constraints. I think that there are many other good alternatives out there at the moment such as the ones we mentioned on Twitter.

I should probably update the README of this repo! :)

Thanks.

**Comment by RevillWeb** [comment]
Just wanted to say @rchrdnsh if you were interested in contributing I could surely find some time to help out :)
